on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - '*' # Push events with a tag

name: Create dataset and create release

jobs:
  build:
    name: Create dataset and create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
      - name: Install package dependencies # This would actually build your project, using zip for an example artifact
        run: |
          pip install -r requirements.txt
      - name: Create dataset # This would actually build your project, using zip for an example artifact
        run: |
          python3 create_customer_data.py
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: create_customer_data.py
